import base64
import json
from pathlib import Path

import pytest

from app.mcp import tools


class FakeResponse:
    def __init__(self, payload: dict):
        self.payload = payload

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, traceback):
        return False

    def read(self) -> bytes:
        return json.dumps(self.payload).encode("utf-8")


class FakeTextResponse:
    def __init__(self, text: str):
        self.text = text

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, traceback):
        return False

    def read(self) -> bytes:
        return self.text.encode("utf-8")


def test_file_write_and_read_are_scoped_to_tool_workspace(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("AGENTFLOW_TOOL_WORKDIR", str(tmp_path))
    monkeypatch.setenv("ORCHESTRATOR_PUBLIC_BASE_URL", "http://localhost:8000")
    content = json.dumps(
        {
            "file_write": {"path": "notes/hello.txt", "content": "hello from tool"},
            "file_read": {"path": "notes/hello.txt"},
        }
    )

    calls = tools.run_allowed_tools({"file_write", "file_read"}, content, {})

    assert [call["toolName"] for call in calls] == ["file_write", "file_read"]
    assert calls[0]["status"] == "COMPLETED"
    assert calls[0]["result"]["bytesWritten"] == len("hello from tool")
    assert calls[0]["result"]["publicUrl"] == "http://localhost:8000/tool-files/notes/hello.txt"
    assert calls[1]["status"] == "COMPLETED"
    assert calls[1]["result"]["content"] == "hello from tool"
    assert (tmp_path / "notes" / "hello.txt").read_text(encoding="utf-8") == "hello from tool"


def test_file_tools_reject_path_traversal(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("AGENTFLOW_TOOL_WORKDIR", str(tmp_path))
    content = json.dumps({"file_read": {"path": "../secret.txt"}})

    calls = tools.run_allowed_tools({"file_read"}, content, {})

    assert calls[0]["status"] == "FAILED"
    assert "escapes" in calls[0]["error"]


def test_file_write_uses_default_desktop_workspace_path_for_plain_text(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("AGENTFLOW_TOOL_WORKDIR", str(tmp_path))

    calls = tools.run_allowed_tools({"file_write"}, "Plain text generated by an agent.", {})

    assert calls[0]["status"] == "COMPLETED"
    assert calls[0]["result"]["path"].startswith("agentflow-output-")
    assert calls[0]["result"]["path"].endswith(".txt")
    assert (tmp_path / calls[0]["result"]["path"]).read_text(encoding="utf-8") == "Plain text generated by an agent."


def test_file_write_supports_base64_binary_content(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("AGENTFLOW_TOOL_WORKDIR", str(tmp_path))
    raw = b"\x89PNG\r\n"
    content = json.dumps(
        {
            "file_write": {
                "path": "images/pixel.png",
                "contentBase64": base64.b64encode(raw).decode("ascii"),
            },
            "file_read": {"path": "images/pixel.png"},
        }
    )

    calls = tools.run_allowed_tools({"file_write", "file_read"}, content, {})

    assert calls[0]["status"] == "COMPLETED"
    assert calls[0]["result"]["binary"] is True
    assert calls[1]["result"]["contentBase64"] == base64.b64encode(raw).decode("ascii")


def test_file_read_finds_similar_file_in_workspace(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("AGENTFLOW_TOOL_WORKDIR", str(tmp_path))
    (tmp_path / "cristo-redentor-notas.md").write_text("Cristo Redentor fica no Corcovado.", encoding="utf-8")

    calls = tools.run_allowed_tools({"file_read"}, "Leia o arquivo sobre cristo redentor", {})

    assert calls[0]["status"] == "COMPLETED"
    assert calls[0]["result"]["path"] == "cristo-redentor-notas.md"
    assert "Corcovado" in calls[0]["result"]["content"]


def test_file_read_fails_when_no_similar_file_exists(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("AGENTFLOW_TOOL_WORKDIR", str(tmp_path))
    (tmp_path / "agenda.txt").write_text("Reuniao as 10h.", encoding="utf-8")

    calls = tools.run_allowed_tools({"file_read"}, "Leia um arquivo sobre Cristo Redentor", {})

    assert calls[0]["status"] == "FAILED"
    assert "No matching file" in calls[0]["error"]


def test_web_search_returns_instant_answer_results(monkeypatch: pytest.MonkeyPatch) -> None:
    def fake_urlopen(request, timeout):
        assert "DuckDuckGo" not in str(request.full_url)
        assert timeout == 8
        return FakeResponse(
            {
                "Heading": "LangGraph",
                "AbstractText": "LangGraph is a framework for building stateful agents.",
                "AbstractURL": "https://example.test/langgraph",
                "RelatedTopics": [{"Text": "StateGraph - graph runtime", "FirstURL": "https://example.test/stategraph"}],
            }
        )

    monkeypatch.setattr(tools.urllib.request, "urlopen", fake_urlopen)
    content = json.dumps({"web_search": {"query": "LangGraph", "maxResults": 2}})

    calls = tools.run_allowed_tools({"web_search"}, content, {})

    assert calls[0]["status"] == "COMPLETED"
    assert calls[0]["result"]["query"] == "LangGraph"
    assert calls[0]["result"]["results"][0]["title"] == "LangGraph"


def test_web_search_falls_back_when_instant_answer_is_not_json(monkeypatch: pytest.MonkeyPatch) -> None:
    def fake_urlopen(request, timeout):
        if "api.duckduckgo.com" in request.full_url:
            return FakeTextResponse("")
        if "html.duckduckgo.com" in request.full_url:
            return FakeTextResponse(
                """
                <a class="result__a" href="https://example.test/cristo">Cristo Redentor</a>
                <a class="result__snippet">Estatua no Rio de Janeiro.</a>
                """
            )
        raise AssertionError(f"Unexpected URL: {request.full_url}")

    monkeypatch.setattr(tools.urllib.request, "urlopen", fake_urlopen)

    calls = tools.run_allowed_tools({"web_search"}, "Cristo Redentor", {})

    assert calls[0]["status"] == "COMPLETED"
    assert calls[0]["result"]["source"] == "duckduckgo_html"
    assert calls[0]["result"]["results"][0]["title"] == "Cristo Redentor"


def test_web_search_falls_back_to_wikipedia(monkeypatch: pytest.MonkeyPatch) -> None:
    def fake_urlopen(request, timeout):
        if "api.duckduckgo.com" in request.full_url:
            return FakeTextResponse("")
        if "html.duckduckgo.com" in request.full_url:
            return FakeTextResponse("<html></html>")
        if "wikipedia.org" in request.full_url:
            return FakeResponse(
                [
                    "Cristo Redentor",
                    ["Christ the Redeemer"],
                    ["Statue in Rio de Janeiro."],
                    ["https://en.wikipedia.org/wiki/Christ_the_Redeemer"],
                ]
            )
        raise AssertionError(f"Unexpected URL: {request.full_url}")

    monkeypatch.setattr(tools.urllib.request, "urlopen", fake_urlopen)

    calls = tools.run_allowed_tools({"web_search"}, "Cristo Redentor", {})

    assert calls[0]["status"] == "COMPLETED"
    assert calls[0]["result"]["source"] == "wikipedia_opensearch"
    assert calls[0]["result"]["results"][0]["url"].endswith("Christ_the_Redeemer")


def test_image_generate_uses_gemini_response_and_writes_image(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    raw_image = b"fake-png"

    def fake_urlopen(request, timeout):
        assert request.headers["X-goog-api-key"] == "test-key"
        assert timeout == 30
        assert "gemini-2.5-flash-image" in request.full_url
        assert json.loads(request.data.decode("utf-8"))["contents"][0]["parts"][0]["text"] == "A clean UI mockup"
        return FakeResponse(
            {
                "candidates": [
                    {
                        "content": {
                            "parts": [
                                {"text": "Generated."},
                                {
                                    "inlineData": {
                                        "mimeType": "image/png",
                                        "data": base64.b64encode(raw_image).decode("ascii"),
                                    }
                                },
                            ]
                        }
                    }
                ]
            }
        )

    monkeypatch.setenv("AGENTFLOW_TOOL_WORKDIR", str(tmp_path))
    monkeypatch.setenv("GEMINI_API_KEY", "test-key")
    monkeypatch.setenv("GEMINI_IMAGE_MODEL", "gemini-2.5-flash-image")
    monkeypatch.setenv("GEMINI_IMAGE_FALLBACK_MODELS", "")
    monkeypatch.setenv("GEMINI_IMAGE_DISCOVERY_ENABLED", "false")
    monkeypatch.setattr(tools.urllib.request, "urlopen", fake_urlopen)
    content = json.dumps({"image_generate": {"prompt": "A clean UI mockup", "path": "images/mock.png"}})

    calls = tools.run_allowed_tools({"image_generate"}, content, {})

    assert calls[0]["status"] == "COMPLETED"
    assert calls[0]["result"]["mimeType"] == "image/png"
    assert calls[0]["result"]["publicUrl"] == "http://localhost:8000/tool-files/images/mock.png"
    assert (tmp_path / "images" / "mock.png").read_bytes() == raw_image


def test_image_generate_uses_plain_text_as_prompt(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    raw_image = b"fake-png"

    def fake_urlopen(request, timeout):
        request_body = json.loads(request.data.decode("utf-8"))
        assert request_body["contents"][0]["parts"][0]["text"] == "Cristo Redentor no Rio de Janeiro"
        return FakeResponse(
            {
                "candidates": [
                    {
                        "content": {
                            "parts": [
                                {
                                    "inlineData": {
                                        "mimeType": "image/png",
                                        "data": base64.b64encode(raw_image).decode("ascii"),
                                    }
                                }
                            ]
                        }
                    }
                ]
            }
        )

    monkeypatch.setenv("AGENTFLOW_TOOL_WORKDIR", str(tmp_path))
    monkeypatch.setenv("GEMINI_API_KEY", "test-key")
    monkeypatch.setenv("GEMINI_IMAGE_MODEL", "gemini-2.5-flash-image")
    monkeypatch.setenv("GEMINI_IMAGE_FALLBACK_MODELS", "")
    monkeypatch.setenv("GEMINI_IMAGE_DISCOVERY_ENABLED", "false")
    monkeypatch.setattr(tools.urllib.request, "urlopen", fake_urlopen)

    calls = tools.run_allowed_tools({"image_generate"}, "Cristo Redentor no Rio de Janeiro", {})

    assert calls[0]["status"] == "COMPLETED"
    assert calls[0]["result"]["path"].startswith("agentflow-image-")
    assert (tmp_path / calls[0]["result"]["path"]).read_bytes() == raw_image


def test_image_generate_extracts_markdown_prompt(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    raw_image = b"fake-png"

    def fake_urlopen(request, timeout):
        request_body = json.loads(request.data.decode("utf-8"))
        assert request_body["contents"][0]["parts"][0]["text"] == "Uma vista panoramica do Rio de Janeiro"
        return FakeResponse(
            {
                "candidates": [
                    {
                        "content": {
                            "parts": [
                                {
                                    "inlineData": {
                                        "mimeType": "image/png",
                                        "data": base64.b64encode(raw_image).decode("ascii"),
                                    }
                                }
                            ]
                        }
                    }
                ]
            }
        )

    monkeypatch.setenv("AGENTFLOW_TOOL_WORKDIR", str(tmp_path))
    monkeypatch.setenv("GEMINI_API_KEY", "test-key")
    monkeypatch.setenv("GEMINI_IMAGE_MODEL", "gemini-2.5-flash-image")
    monkeypatch.setenv("GEMINI_IMAGE_FALLBACK_MODELS", "")
    monkeypatch.setenv("GEMINI_IMAGE_DISCOVERY_ENABLED", "false")
    monkeypatch.setattr(tools.urllib.request, "urlopen", fake_urlopen)
    content = '**Prompt para Geracao de Imagem:** "Uma vista panoramica do Rio de Janeiro"'

    calls = tools.run_allowed_tools({"image_generate"}, content, {})

    assert calls[0]["status"] == "COMPLETED"


def test_image_generate_discovers_google_image_models(monkeypatch: pytest.MonkeyPatch) -> None:
    def fake_urlopen(request, timeout):
        assert request.full_url.endswith("/v1beta/models")
        return FakeResponse(
            {
                "models": [
                    {
                        "name": "models/gemini-3.1-flash-image-preview",
                        "displayName": "Nano Banana 2",
                        "supportedGenerationMethods": ["generateContent"],
                    },
                    {
                        "name": "models/gemini-2.5-flash",
                        "displayName": "Gemini 2.5 Flash",
                        "supportedGenerationMethods": ["generateContent"],
                    },
                    {
                        "name": "models/imagen-4.0-fast-generate-001",
                        "displayName": "Imagen 4 Fast",
                        "supportedGenerationMethods": ["predict"],
                    },
                ]
            }
        )

    monkeypatch.delenv("GEMINI_IMAGE_MODEL", raising=False)
    monkeypatch.delenv("GEMINI_IMAGE_FALLBACK_MODELS", raising=False)
    monkeypatch.setenv("GEMINI_IMAGE_DISCOVERY_ENABLED", "true")
    monkeypatch.setattr(tools.urllib.request, "urlopen", fake_urlopen)

    models = tools.configured_google_image_models("test-key")

    assert models[0] == "gemini-3.1-flash-image-preview"
    assert "gemini-2.5-flash" not in models
    assert "imagen-4.0-fast-generate-001" in models


def test_image_generate_requires_configured_gemini_key(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.delenv("GEMINI_API_KEY", raising=False)
    content = json.dumps({"image_generate": {"prompt": "A clean UI mockup"}})

    calls = tools.run_allowed_tools({"image_generate"}, content, {})

    assert calls[0]["status"] == "FAILED"
    assert "GEMINI_API_KEY" in calls[0]["error"]


def test_image_generate_tries_fallback_models(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    raw_image = b"fake-png"
    requested_urls: list[str] = []

    def fake_urlopen(request, timeout):
        requested_urls.append(request.full_url)
        if "missing-model" in request.full_url:
            raise tools.ToolExecutionError("Gemini model missing-model failed with HTTP 404")
        return FakeResponse(
            {
                "candidates": [
                    {
                        "content": {
                            "parts": [
                                {
                                    "inlineData": {
                                        "mimeType": "image/png",
                                        "data": base64.b64encode(raw_image).decode("ascii"),
                                    }
                                }
                            ]
                        }
                    }
                ]
            }
        )

    monkeypatch.setenv("AGENTFLOW_TOOL_WORKDIR", str(tmp_path))
    monkeypatch.setenv("GEMINI_API_KEY", "test-key")
    monkeypatch.setenv("GEMINI_IMAGE_MODEL", "missing-model")
    monkeypatch.setenv("GEMINI_IMAGE_FALLBACK_MODELS", "gemini-2.5-flash-image")
    monkeypatch.setenv("GEMINI_IMAGE_DISCOVERY_ENABLED", "false")
    monkeypatch.setattr(tools.urllib.request, "urlopen", fake_urlopen)

    calls = tools.run_allowed_tools({"image_generate"}, "A clean UI mockup", {})

    assert calls[0]["status"] == "COMPLETED"
    assert calls[0]["result"]["model"] == "gemini-2.5-flash-image"
    assert len(requested_urls) == 2


def test_image_generate_supports_imagen_predict_response(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    raw_image = b"fake-png"

    def fake_urlopen(request, timeout):
        assert "imagen-4.0-fast-generate-001%3Apredict" not in request.full_url
        assert "imagen-4.0-fast-generate-001" in request.full_url
        request_body = json.loads(request.data.decode("utf-8"))
        assert request_body["instances"][0]["prompt"] == "A clean UI mockup"
        assert request_body["parameters"]["sampleCount"] == 1
        return FakeResponse(
            {
                "predictions": [
                    {
                        "bytesBase64Encoded": base64.b64encode(raw_image).decode("ascii"),
                        "mimeType": "image/png",
                    }
                ]
            }
        )

    monkeypatch.setenv("AGENTFLOW_TOOL_WORKDIR", str(tmp_path))
    monkeypatch.setenv("GEMINI_API_KEY", "test-key")
    monkeypatch.setenv("GEMINI_IMAGE_MODEL", "imagen-4.0-fast-generate-001")
    monkeypatch.setenv("GEMINI_IMAGE_FALLBACK_MODELS", "")
    monkeypatch.setenv("GEMINI_IMAGE_DISCOVERY_ENABLED", "false")
    monkeypatch.setattr(tools.urllib.request, "urlopen", fake_urlopen)

    calls = tools.run_allowed_tools({"image_generate"}, "A clean UI mockup", {})

    assert calls[0]["status"] == "COMPLETED"
    assert calls[0]["result"]["model"] == "imagen-4.0-fast-generate-001"
    assert (tmp_path / calls[0]["result"]["path"]).read_bytes() == raw_image
