import base64
import json
from pathlib import Path

import pytest

from app.mcp import tools


class FakeResponse:
    def __init__(self, payload: dict):
        self.payload = payload

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, traceback):
        return False

    def read(self) -> bytes:
        return json.dumps(self.payload).encode("utf-8")


class FakeTextResponse:
    def __init__(self, text: str):
        self.text = text

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, traceback):
        return False

    def read(self) -> bytes:
        return self.text.encode("utf-8")


def test_file_write_and_read_are_scoped_to_tool_workspace(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("AGENTFLOW_TOOL_WORKDIR", str(tmp_path))
    monkeypatch.setenv("ORCHESTRATOR_PUBLIC_BASE_URL", "http://localhost:8000")
    content = json.dumps(
        {
            "file_write": {"path": "notes/hello.txt", "content": "hello from tool"},
            "file_read": {"path": "notes/hello.txt"},
        }
    )

    calls = tools.run_allowed_tools({"file_write", "file_read"}, content, {})

    assert [call["toolName"] for call in calls] == ["file_write", "file_read"]
    assert calls[0]["status"] == "COMPLETED"
    assert calls[0]["result"]["bytesWritten"] == len("hello from tool")
    assert calls[0]["result"]["publicUrl"] == "http://localhost:8000/tool-files/notes/hello.txt"
    assert calls[1]["status"] == "COMPLETED"
    assert calls[1]["result"]["content"] == "hello from tool"
    assert (tmp_path / "notes" / "hello.txt").read_text(encoding="utf-8") == "hello from tool"


def test_file_tools_reject_path_traversal(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("AGENTFLOW_TOOL_WORKDIR", str(tmp_path))
    content = json.dumps({"file_read": {"path": "../secret.txt"}})

    calls = tools.run_allowed_tools({"file_read"}, content, {})

    assert calls[0]["status"] == "FAILED"
    assert "escapes" in calls[0]["error"]


def test_file_write_uses_contextual_workspace_path_for_plain_text(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("AGENTFLOW_TOOL_WORKDIR", str(tmp_path))

    calls = tools.run_allowed_tools({"file_write"}, "Plain text generated by an agent.", {})

    assert calls[0]["status"] == "COMPLETED"
    assert calls[0]["result"]["path"].startswith("plain-text-generated-agent-")
    assert calls[0]["result"]["path"].endswith(".txt")
    assert (tmp_path / calls[0]["result"]["path"]).read_text(encoding="utf-8") == "Plain text generated by an agent."


def test_file_write_supports_base64_binary_content(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("AGENTFLOW_TOOL_WORKDIR", str(tmp_path))
    raw = b"\x89PNG\r\n"
    content = json.dumps(
        {
            "file_write": {
                "path": "images/pixel.png",
                "contentBase64": base64.b64encode(raw).decode("ascii"),
            },
            "file_read": {"path": "images/pixel.png"},
        }
    )

    calls = tools.run_allowed_tools({"file_write", "file_read"}, content, {})

    assert calls[0]["status"] == "COMPLETED"
    assert calls[0]["result"]["binary"] is True
    assert calls[1]["result"]["contentBase64"] == base64.b64encode(raw).decode("ascii")


def test_file_read_finds_similar_file_in_workspace(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("AGENTFLOW_TOOL_WORKDIR", str(tmp_path))
    (tmp_path / "cristo-redentor-notas.md").write_text("Cristo Redentor fica no Corcovado.", encoding="utf-8")

    calls = tools.run_allowed_tools({"file_read"}, "Leia o arquivo sobre cristo redentor", {})

    assert calls[0]["status"] == "COMPLETED"
    assert calls[0]["result"]["path"] == "cristo-redentor-notas.md"
    assert "Corcovado" in calls[0]["result"]["content"]


def test_file_read_chooses_best_similar_filename(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("AGENTFLOW_TOOL_WORKDIR", str(tmp_path))
    (tmp_path / "cristo-redentor-notas.txt").write_text("Cristo Redentor fica no Corcovado.", encoding="utf-8")
    (tmp_path / "muralha-da-china-piada.txt").write_text("Por que a Muralha da China nunca se perde?", encoding="utf-8")

    calls = tools.run_allowed_tools({"file_read"}, "Leia o arquivo sobre muralha china", {})

    assert calls[0]["status"] == "COMPLETED"
    assert calls[0]["result"]["path"] == "muralha-da-china-piada.txt"
    assert "Muralha da China" in calls[0]["result"]["content"]


def test_file_read_does_not_search_by_file_content(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("AGENTFLOW_TOOL_WORKDIR", str(tmp_path))
    (tmp_path / "nota-001.txt").write_text(
        "O Cristo Redentor fica no Corcovado e observa a cidade do Rio de Janeiro.",
        encoding="utf-8",
    )

    calls = tools.run_allowed_tools({"file_read"}, "Leia algum arquivo relacionado ao Corcovado", {})

    assert calls[0]["status"] == "FAILED"
    assert "No matching file" in calls[0]["error"]


def test_file_read_fails_when_no_similar_file_exists(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("AGENTFLOW_TOOL_WORKDIR", str(tmp_path))
    (tmp_path / "agenda.txt").write_text("Reuniao as 10h.", encoding="utf-8")

    calls = tools.run_allowed_tools({"file_read"}, "Leia um arquivo sobre Cristo Redentor", {})

    assert calls[0]["status"] == "FAILED"
    assert "No matching file" in calls[0]["error"]


def test_web_search_returns_instant_answer_results(monkeypatch: pytest.MonkeyPatch) -> None:
    def fake_urlopen(request, timeout):
        assert "DuckDuckGo" not in str(request.full_url)
        assert timeout == 8
        return FakeResponse(
            {
                "Heading": "LangGraph",
                "AbstractText": "LangGraph is a framework for building stateful agents.",
                "AbstractURL": "https://example.test/langgraph",
                "RelatedTopics": [{"Text": "StateGraph - graph runtime", "FirstURL": "https://example.test/stategraph"}],
            }
        )

    monkeypatch.setattr(tools.urllib.request, "urlopen", fake_urlopen)
    content = json.dumps({"web_search": {"query": "LangGraph", "maxResults": 2}})

    calls = tools.run_allowed_tools({"web_search"}, content, {})

    assert calls[0]["status"] == "COMPLETED"
    assert calls[0]["result"]["query"] == "LangGraph"
    assert calls[0]["result"]["results"][0]["title"] == "LangGraph"


def test_web_search_falls_back_when_instant_answer_is_not_json(monkeypatch: pytest.MonkeyPatch) -> None:
    def fake_urlopen(request, timeout):
        if "api.duckduckgo.com" in request.full_url:
            return FakeTextResponse("")
        if "html.duckduckgo.com" in request.full_url:
            return FakeTextResponse(
                """
                <a class="result__a" href="https://example.test/cristo">Cristo Redentor</a>
                <a class="result__snippet">Estatua no Rio de Janeiro.</a>
                """
            )
        raise AssertionError(f"Unexpected URL: {request.full_url}")

    monkeypatch.setattr(tools.urllib.request, "urlopen", fake_urlopen)

    calls = tools.run_allowed_tools({"web_search"}, "Cristo Redentor", {})

    assert calls[0]["status"] == "COMPLETED"
    assert calls[0]["result"]["source"] == "duckduckgo_html"
    assert calls[0]["result"]["results"][0]["title"] == "Cristo Redentor"


def test_web_search_falls_back_to_wikipedia(monkeypatch: pytest.MonkeyPatch) -> None:
    def fake_urlopen(request, timeout):
        if "api.duckduckgo.com" in request.full_url:
            return FakeTextResponse("")
        if "html.duckduckgo.com" in request.full_url:
            return FakeTextResponse("<html></html>")
        if "wikipedia.org" in request.full_url:
            return FakeResponse(
                [
                    "Cristo Redentor",
                    ["Christ the Redeemer"],
                    ["Statue in Rio de Janeiro."],
                    ["https://en.wikipedia.org/wiki/Christ_the_Redeemer"],
                ]
            )
        raise AssertionError(f"Unexpected URL: {request.full_url}")

    monkeypatch.setattr(tools.urllib.request, "urlopen", fake_urlopen)

    calls = tools.run_allowed_tools({"web_search"}, "Cristo Redentor", {})

    assert calls[0]["status"] == "COMPLETED"
    assert calls[0]["result"]["source"] == "wikipedia_opensearch"
    assert calls[0]["result"]["results"][0]["url"].endswith("Christ_the_Redeemer")


class FakeImage:
    def __init__(self, content: bytes = b"fake-png"):
        self.content = content

    def save(self, target: Path, format: str | None = None) -> None:
        assert format in {"PNG", "JPEG", "WEBP"}
        target.write_bytes(self.content)


def test_image_generate_uses_huggingface_and_writes_image(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    def fake_generate(provider: str, api_key: str, model: str, prompt: str):
        assert provider == "wavespeed"
        assert api_key == "test-token"
        assert model == "black-forest-labs/FLUX.1-dev"
        assert prompt == "A clean UI mockup"
        return FakeImage()

    monkeypatch.setenv("AGENTFLOW_TOOL_WORKDIR", str(tmp_path))
    monkeypatch.setenv("ORCHESTRATOR_PUBLIC_BASE_URL", "http://localhost:8000")
    monkeypatch.setenv("HF_TOKEN", "test-token")
    monkeypatch.delenv("HF_IMAGE_PROVIDER", raising=False)
    monkeypatch.delenv("HF_IMAGE_MODEL", raising=False)
    monkeypatch.delenv("HF_IMAGE_FALLBACKS", raising=False)
    monkeypatch.setattr(tools, "generate_huggingface_image", fake_generate)
    content = json.dumps({"image_generate": {"prompt": "A clean UI mockup", "path": "images/mock.png"}})

    calls = tools.run_allowed_tools({"image_generate"}, content, {})

    assert calls[0]["status"] == "COMPLETED"
    assert calls[0]["result"]["provider"] == "wavespeed"
    assert calls[0]["result"]["model"] == "black-forest-labs/FLUX.1-dev"
    assert calls[0]["result"]["mimeType"] == "image/png"
    assert calls[0]["result"]["publicUrl"] == "http://localhost:8000/tool-files/images/mock.png"
    assert (tmp_path / "images" / "mock.png").read_bytes() == b"fake-png"


def test_image_generate_falls_back_when_primary_provider_has_no_quota(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    attempted: list[tuple[str, str]] = []

    def fake_generate(provider: str, api_key: str, model: str, prompt: str):
        attempted.append((provider, model))
        if provider == "wavespeed":
            raise RuntimeError("402 Payment Required")
        assert provider == "hf-inference"
        assert model == "black-forest-labs/FLUX.1-schnell"
        return FakeImage(b"fallback-png")

    monkeypatch.setenv("AGENTFLOW_TOOL_WORKDIR", str(tmp_path))
    monkeypatch.setenv("HF_TOKEN", "test-token")
    monkeypatch.setenv("HF_IMAGE_PROVIDER", "wavespeed")
    monkeypatch.setenv("HF_IMAGE_MODEL", "black-forest-labs/FLUX.1-dev")
    monkeypatch.setenv("HF_IMAGE_FALLBACKS", "hf-inference|black-forest-labs/FLUX.1-schnell")
    monkeypatch.setattr(tools, "generate_huggingface_image", fake_generate)

    calls = tools.run_allowed_tools({"image_generate"}, json.dumps({"image_generate": {"prompt": "A clean UI mockup"}}), {})

    assert calls[0]["status"] == "COMPLETED"
    assert attempted == [
        ("wavespeed", "black-forest-labs/FLUX.1-dev"),
        ("hf-inference", "black-forest-labs/FLUX.1-schnell"),
    ]
    assert calls[0]["result"]["provider"] == "hf-inference"
    assert calls[0]["result"]["model"] == "black-forest-labs/FLUX.1-schnell"
    assert [attempt["status"] for attempt in calls[0]["result"]["attempts"]] == ["FAILED", "COMPLETED"]
    assert (tmp_path / calls[0]["result"]["path"]).read_bytes() == b"fallback-png"


def test_image_generate_allows_huggingface_provider_and_model_overrides(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    def fake_generate(provider: str, api_key: str, model: str, prompt: str):
        assert provider == "fal-ai"
        assert model == "custom/model"
        assert prompt == "A clean UI mockup"
        return FakeImage()

    monkeypatch.setenv("AGENTFLOW_TOOL_WORKDIR", str(tmp_path))
    monkeypatch.setenv("HF_TOKEN", "test-token")
    monkeypatch.setattr(tools, "generate_huggingface_image", fake_generate)
    content = json.dumps(
        {"image_generate": {"prompt": "A clean UI mockup", "provider": "fal-ai", "model": "custom/model"}}
    )

    calls = tools.run_allowed_tools({"image_generate"}, content, {})

    assert calls[0]["status"] == "COMPLETED"
    assert calls[0]["result"]["provider"] == "fal-ai"
    assert calls[0]["result"]["model"] == "custom/model"


def test_image_generate_uses_plain_text_as_prompt(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    def fake_generate(provider: str, api_key: str, model: str, prompt: str):
        assert prompt == "Cristo Redentor no Rio de Janeiro"
        return FakeImage()

    monkeypatch.setenv("AGENTFLOW_TOOL_WORKDIR", str(tmp_path))
    monkeypatch.setenv("HF_TOKEN", "test-token")
    monkeypatch.setattr(tools, "generate_huggingface_image", fake_generate)

    calls = tools.run_allowed_tools({"image_generate"}, "Cristo Redentor no Rio de Janeiro", {})

    assert calls[0]["status"] == "COMPLETED"
    assert calls[0]["result"]["path"].startswith("agentflow-image-")
    assert (tmp_path / calls[0]["result"]["path"]).read_bytes() == b"fake-png"


def test_image_generate_extracts_markdown_prompt(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    def fake_generate(provider: str, api_key: str, model: str, prompt: str):
        assert prompt == "Uma vista panoramica do Rio de Janeiro"
        return FakeImage()

    monkeypatch.setenv("AGENTFLOW_TOOL_WORKDIR", str(tmp_path))
    monkeypatch.setenv("HF_TOKEN", "test-token")
    monkeypatch.setattr(tools, "generate_huggingface_image", fake_generate)
    content = '**Prompt para Geracao de Imagem:** "Uma vista panoramica do Rio de Janeiro"'

    calls = tools.run_allowed_tools({"image_generate"}, content, {})

    assert calls[0]["status"] == "COMPLETED"


def test_image_generate_requires_configured_hf_token(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.delenv("HF_TOKEN", raising=False)
    content = json.dumps({"image_generate": {"prompt": "A clean UI mockup"}})

    calls = tools.run_allowed_tools({"image_generate"}, content, {})

    assert calls[0]["status"] == "FAILED"
    assert "HF_TOKEN" in calls[0]["error"]


def test_image_save_format_is_derived_from_extension() -> None:
    assert tools.image_save_format(Path("image.png")) == "PNG"
    assert tools.image_save_format(Path("image.jpg")) == "JPEG"
    assert tools.image_save_format(Path("image.webp")) == "WEBP"
    assert tools.image_save_format(Path("image")) == "PNG"
